### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [rnadigital/monita-global-gtm-template#1]
https://github.com/rnadigital/monita-global-gtm-template/blob/0f2c335cbc430409d9cb24318f8f56ae6f18ab66/template.tpl#LL80C61-L80C71

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by pebeid** [comment]
Thank you. I've fixed the issue in RELEASE-1.0.1
